---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: goyo-ns
  name: goyo-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-name: goyo-alb
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goyo-nginx-svc
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: goyo-ns
  name: goyo-nginx-deploy
  labels:
    app: goyo-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goyo-nginx
  template:
    metadata:
      labels:
        app: goyo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: goyo-ns
  name: goyo-nginx-svc
spec:
  selector:
    app: goyo-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80